name: Build and Deploy

on:
  push:
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build docker
        run: |
          docker build  -t prenoms .

      - name: Docker login
        run: |
          docker login -u gnartiub -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker tag
        run: docker tag prenoms gnartiub/prenoms:${{ github.sha }}

      - name: Docker push
        run: docker push gnartiub/prenoms:${{ github.sha }}