name: Build and Deploy

on:
  push:
    branches:
      - 'main'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gcloud
          gcloud auth configure-docker

      - name: Push Docker image to GCR
        run: |
          docker tag flask-app gcr.io/ensai-2024/prenom-prediction-api
          docker push gcr.io/ensai-2024/prenom-prediction-api