name: Build and Deploy

on:
  push:
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build docker
        run: |
          docker build  -t prenoms .

      - name: Docker login
        run: |
          docker login -u gnartiub -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker tag
        run: docker tag prenoms gnartiub/prenoms:${{ github.sha }}

      - name: Docker push
        run: docker push gnartiub/prenoms:${{ github.sha }}

      - name: Auth GCP gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Check if Compute Instance 'prenoms-api-christophe' exists
        id: check
        run: echo "INSTANCE_EXISTS=$(gcloud compute instances list | grep prenoms-api-christophe | wc -l | xargs)" >> "$GITHUB_OUTPUT"


      - name: create (for the first time) API to GCP compute instance
        run: |
          gcloud compute instances create-with-container prenoms-trang \
          --container-image gnartiub/prenoms:${{ github.sha }} \
          --zone europe-west1-b \
          --container-env FLASK_PORT=80


      - name: API to GCP compute instance
        run: |
          gcloud compute instances update-container prenoms-trang \
          --container-image gnartiub/prenoms:${{ github.sha }} \
          --zone europe-west1-b \
          --container-env FLASK_PORT=80


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no buiquynhtrang1234@ensai-2024.iam.gserviceaccount.com 'docker pull gnartiub/prenoms:${{ github.sha }}'